parameters:
    pim_api.controller.attribute.class: Piivo\Bundle\ConnectorBundle\Controller\AttributeController
    pim_api.controller.category.class: Piivo\Bundle\ConnectorBundle\Controller\CategoryController
    pim_api.controller.family.class: Piivo\Bundle\ConnectorBundle\Controller\FamilyController

services:
    piivo_connector.controller.version:
        class: Piivo\Bundle\ConnectorBundle\Controller\VersionController
        arguments:
            - '@piivo_connector.repository.version'
            - '@pim_serializer'
            - '@router'
            - '@pim_api.pagination.offset_hal_paginator'
            - '@pim_api.pagination.parameter_validator'
            - '%pim_api.configuration%'