parameters:
    pim_api.controller.attribute.class: Piivo\Bundle\ConnectorBundle\Controller\AttributeController
    pim_api.controller.category.class: Piivo\Bundle\ConnectorBundle\Controller\CategoryController
    pim_api.controller.family.class: Piivo\Bundle\ConnectorBundle\Controller\FamilyController

services:
    piivo_connector.controller.version:
        class: Piivo\Bundle\ConnectorBundle\Controller\VersionController
        arguments:
            - '@piivo_connector.repository.version'
            - '@pim_catalog.repository.attribute'
            - '%pim_api.configuration%'

    piivo_connector.controller.attribute_option:
        class: Piivo\Bundle\ConnectorBundle\Controller\AttributeOptionController
        arguments:
            - '@pim_catalog.query.product_model_query_builder_factory'
            - '@pim_catalog.saver.product_model'
            - '@pim_catalog.query.product_query_builder_factory'
            - '@pim_catalog.saver.product'
            - '@pim_catalog.repository.attribute'
            - '%pim_api.configuration%'
