parameters:
    pim_api.controller.attribute.class: Piivo\Bundle\ConnectorBundle\Controller\AttributeController
    pim_api.controller.category.class: Piivo\Bundle\ConnectorBundle\Controller\CategoryController