services:
    pim_api.repository.category:
            class: Piivo\Bundle\ConnectorBundle\Repository\CategoryRepository
            arguments:
                - '@doctrine.orm.entity_manager'
                - '%pim_catalog.entity.category.class%'
                - '@pim_catalog.repository.category'
