piivo_api_version_deleted_list:
    path: /rest/v1/versions/deleted/{entityName}
    defaults: { _controller: piivo_connector.controller.version:listAction, _format: json }
    methods: [GET]

piivo_api_text_collection_item_delete:
    path: /rest/v1/attributes/{attributeCode}/items/{item}
    defaults: { _controller: piivo_connector.controller.attribute_option:deleteItemAction, _format: json }
    methods: [DELETE]